'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),prefix='/404Experiments/';
const files=fs.readdirSync(root).filter(x=>/^\d\d-/.test(x)).map(x=>x+(x.startsWith('04-')?'/index.html':'')+'/index.html').concat(fs.readdirSync(path.join(root,'apis')).filter(x=>fs.existsSync(path.join(root,'apis',x,'index.html'))).map(x=>'apis/'+x+'/index.html'));
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith(prefix))return res.writeHead(404).end();const file=path.resolve(root,decodeURIComponent(url.pathname.slice(prefix.length)));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'application/javascript'})[path.extname(file)]||'text/plain');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch();try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.fulfill({status:200,contentType:'application/json',body:'{}'}));
for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});for(const file of ['apis/index.html','experiments/index.html',...files]){await page.goto(origin+prefix+file);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${file} overflow ${width}`);
if(files.includes(file)){const links=page.locator('.connected-list a');assert.ok([2,3].includes(await links.count()),file);for(const href of await links.evaluateAll(a=>a.map(x=>x.href))){assert.ok(href.startsWith(origin+prefix));assert.equal((await page.request.get(href)).status(),200,href);}await links.first().focus();await page.keyboard.press('Tab');assert.equal(await links.nth(1).evaluate(a=>a===document.activeElement&&getComputedStyle(a).outlineStyle==='solid'),true,file+' keyboard focus');assert.ok((await links.first().boundingBox()).height>=44);}
if(file==='apis/index.html'){assert.equal(await page.locator('.signal-lost').count(),2);assert.equal(await page.locator('.signal-lost a,.signal-lost button,.signal-lost [tabindex]').count(),0);assert.deepEqual(await page.locator('.experiment-number').allTextContents(),['01','02','03','04 // SIGNAL LOST','05 // SIGNAL LOST','06 // NASA OBSERVATION','07 // ECONOMIC OBSERVATION']);const card=page.locator('.signal-lost').first();await card.hover();assert.equal(await card.evaluate(a=>getComputedStyle(a).transform),'none');assert.match(await page.locator('.overview-intro .section-index').innerText(),/05 active signals \/ 02 lost channels/i);}
if(file==='experiments/index.html'){assert.deepEqual(await page.locator('.lab-section').first().locator('.experiment-number').allTextContents(),['07','08','09','10']);assert.deepEqual(await page.locator('.early-builds .experiment-number').allTextContents(),['01','02','03','04','05','06']);for(const href of await page.locator('.experiment-card a').evaluateAll(a=>a.map(x=>x.href)))assert.equal((await page.request.get(href)).status(),200);}
if(['apis/index.html','experiments/index.html','08-pt100-converter/index.html'].includes(file)){await page.screenshot({path:path.join(os.tmpdir(),`404-structure-${width}-${file.split('/')[0]}.png`),fullPage:true});}
}}assert.deepEqual(errors,[]);console.log(`PASS: ${files.length} connected pages, exact LAB grouping, lost-channel semantics, routes under ${prefix}, keyboard focus, 1440/768/390px, no uncaught JavaScript errors (controlled unavailable sources).`);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
